### ISSUE TITLE
Compilation error message after updating from Angular 9.1.3 to 9.1.5

### ISSUE THREAD

**Issue by tunereo-firebase** [danielmoncada/date-time-picker#41]
ERROR in node_modules/@danielmoncada/angular-datetime-picker/danielmoncada-angular-datetime-picker.d.ts:17:42 - error TS1149: File name 'node_modules/@danielmoncada/angular-datetime-picker/lib/date-time/numberedFixLen.pipe.d.ts' differs from already included file name 'node_modules/@danielmoncada/angular-datetime-picker/lib/date-time/numberedfixlen.pipe.d.ts' only in casing.

17 export { NumberFixedLenPipe as ɵu } from './lib/date-time/numberedFixLen.pipe';

Application runs fine, but I thought this might be of your interest.

**Looking at source code:**
"lib/date-time/date-time.module.d.ts:16" 
contains "import * as ɵngcc12 from './numberedfixlen.pipe';"

"danielmoncada-angular-datetime-picker.d.ts:17"
contains export { NumberFixedLenPipe as ɵu } from './lib/date-time/numberedFixLen.pipe';

New version of ngcc is adding "numberedfixlen.pipe" to date-time.module.d.ts old one was adding "numberedFixLen.pipe"

**Comment by fastcurveservices-ankit** [comment]
Hi, Please update 9.1.6 for the same.

**Comment by danielmoncada** [comment]
@tunereo-firebase, will update it next release
